### ISSUE TITLE
getting error "Seedbox Error. Download File is Not a Torrent"

### ISSUE THREAD

**Issue by GovPerm** [xirvik/seedbox_firefox_extension#10]
Getting the error above when trying to send to my seedbox. happens on public and private trackers. Worked for the first 3 times and then stopped.

**Comment by simonc56** [comment]
Check issue #6
Did you enable third party cookies?

**Comment by GovPerm** [comment]
I believe I have. It seems to be an issue with the bittorrent client. Magnet links work fine, which can be enabled in the xirvik options. But regardless of how I try and get the .torrent url into the bittorrent client, it doesn't seem to want to take it, just magnet links. It's awfully strange as I never used to have this problem, but I tried two bittorrent clients (deluge and rutorrent) and both have the issue as not recognizing .torrent urls/files as torrent files and therefore will not accept them to download. I'm sure I'm missing something here, but it is defintely not a xirvik issue so, I'll close this issue down if I can and keep working with my seedbox service to see if we can figure this out.
