### ISSUE TITLE
Fancybox issues [BUG]

### ISSUE THREAD

**Issue by vladc** [xirvik/seedbox_firefox_extension#11]
I noticed some websites that use the jQuery plugin Fancybox no longer work properly when this extension is enabled.

Example: https://www.techpowerup.com/257911/intel-plans-to-launch-its-discrete-gpu-lineup-starting-at-usd-200
Clicking on the image with the extension enabled doesn't open the Fancybox modal, as expected.

**Comment by Novik** [comment]
Fixed, thanks for detailed report.
Will be uploaded to the store as soon as possible.
